# Generated by Django 3.0.5 on 2020-07-18 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=None)),
                ('deletedAt', models.DateTimeField(default=None)),
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=120)),
                ('companyType', models.CharField(default=None, max_length=19)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('fileNumber', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=None)),
                ('deletedAt', models.DateTimeField(default=None)),
                ('filerId', models.AutoField(primary_key=True, serialize=False)),
                ('fileType', models.CharField(max_length=4)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Company')),
            ],
            options={
                'ordering': ['companyId'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyHolding',
            fields=[
                ('quarter', models.IntegerField()),
                ('filingType', models.CharField(max_length=3)),
                ('filedOn', models.IntegerField()),
                ('acceptedAt', models.IntegerField()),
                ('valueTotal', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=None)),
                ('deletedAt', models.DateTimeField(default=None)),
                ('quarterId', models.AutoField(primary_key=True, serialize=False)),
                ('filerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Filer')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyOtherManager',
            fields=[
                ('number', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=None)),
                ('deletedAt', models.DateTimeField(default=None)),
                ('otherManagerId', models.AutoField(primary_key=True, serialize=False)),
                ('childFilerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_Filer', to='restapi.Filer')),
                ('parentFilerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_Filer', to='restapi.Filer')),
                ('quarterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.QuarterlyHolding')),
            ],
            options={
                'ordering': ['quarterId'],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('CUSIP', models.IntegerField()),
                ('securityName', models.CharField(max_length=40)),
                ('securityType', models.CharField(max_length=7)),
                ('ticker', models.CharField(max_length=5)),
                ('titleOfClass', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=None)),
                ('deletedAt', models.DateTimeField(default=None)),
                ('securityId', models.AutoField(primary_key=True, serialize=False)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Company')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlySecurityHolding',
            fields=[
                ('value', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('holdingType', models.CharField(max_length=3)),
                ('investmentDiscretion', models.CharField(max_length=5)),
                ('sole', models.IntegerField()),
                ('shared', models.IntegerField()),
                ('none', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=None)),
                ('deletedAt', models.DateTimeField(default=None)),
                ('quarterlySecurityHoldingId', models.AutoField(primary_key=True, serialize=False)),
                ('quarterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.QuarterlyHolding')),
                ('securityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Security')),
            ],
            options={
                'ordering': ['quarterId'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyOtherManagerDistribution',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=None)),
                ('deletedAt', models.DateTimeField(default=None)),
                ('quarterlyOtherManagerDistributionId', models.AutoField(primary_key=True, serialize=False)),
                ('quarterlyOtherManagerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.QuarterlyOtherManager')),
                ('quarterlySecurityHoldingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.QuarterlySecurityHolding')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
