"""
Django settings for fedgehundapi project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import socket
import environ

env = environ.Env()
# reading .env file
environ.Env.read_env()

# If the host name ends with 'local', DJANGO_ENV = "development"
if socket.gethostname().endswith('local'):
    DJANGO_ENV = "development"
# Else if host name starts with 'test', set DJANGO_ENV = "test"
elif socket.gethostname().startswith('test'): 
    DJANGO_ENV = "testing"
else:
# If host doesn't match, assume it's a production server, set DJANGO_ENV = "production"
    DJANGO_ENV = "production"

# Define general behavior variables for DJANGO_ENV and all others
# SECURITY WARNING: don't run with debug turned on in production!
if DJANGO_ENV == "production":
    DEBUG = True #Change this to false when deploying final app
else:
    DEBUG = True

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if DJANGO_ENV == "production":
# Use hosted remote DB in production
    DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': env("PRODUCTION_DB_NAME"),
            'CLIENT': {
                'host': env("HOST_IP"),
                'port': env("HOST_PORT"),
                'username': env("PRODUCTION_DB_USERNAME"),
                'password': env("PRODUCTION_DB_PASSWORD"),
                'authSource': env("PRODUCTION_DB_NAME"),
            },
        }
    }
else: 
# Use local DB in development
    DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': env('LOCAL_DB_NAME'),
        }
    }

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')


ALLOWED_HOSTS = ['mrktdbapi-PROD.eba-ae6apzne.us-west-2.elasticbeanstalk.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'testapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fedgehundapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fedgehundapi.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'