# Generated by Django 3.0.5 on 2020-07-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='filer',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='filer',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quarterlyholding',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quarterlyholding',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quarterlyothermanager',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quarterlyothermanager',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quarterlyothermanagerdistribution',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quarterlyothermanagerdistribution',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quarterlysecurityholding',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quarterlysecurityholding',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='security',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='security',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
