# Generated by Django 3.0.5 on 2021-02-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['ticker'], 'verbose_name_plural': 'Securities'},
        ),
        migrations.AlterField(
            model_name='cikcusipmapping',
            name='cikCusipMappingId',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='cik',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='filer',
            name='companyId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='edgar.Company'),
        ),
        migrations.AlterField(
            model_name='filer',
            name='fileNumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='filer',
            name='fileType',
            field=models.CharField(blank=True, choices=[('13F', '13F'), ('13G', '13G'), ('13D', '13D')], max_length=3),
        ),
        migrations.AlterField(
            model_name='quarterlyholding',
            name='acceptedAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='quarterlyholding',
            name='deletedAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='quarterlyholding',
            name='filedOn',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='quarterlyholding',
            name='filingType',
            field=models.CharField(choices=[('CR', 'Combined Report'), ('CRA', 'Combined Report Amendment'), ('NT', 'Notice'), ('NTA', 'Notice Amendment'), ('HR', 'Holdings Report'), ('HRA', 'Holdings Report Amendment')], max_length=3),
        ),
        migrations.AlterField(
            model_name='quarterlyothermanager',
            name='childFilerId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_filer', to='edgar.Filer'),
        ),
        migrations.AlterField(
            model_name='quarterlyothermanager',
            name='parentFilerId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_filer', to='edgar.Filer'),
        ),
        migrations.AlterField(
            model_name='quarterlysecurityholding',
            name='holdingType',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quarterlysecurityholding',
            name='uin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='security',
            name='cikCusipMappingId',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
