# Generated by Django 3.0.5 on 2020-08-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterlyholding',
            name='acceptedAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='quarterlyholding',
            name='filedOn',
            field=models.DateTimeField(blank=True),
        ),
    ]
