# Generated by Django 3.0.5 on 2020-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['ticker'], 'verbose_name_plural': 'Securities'},
        ),
        migrations.RemoveField(
            model_name='quarterlyholding',
            name='acceptedAt',
        ),
        migrations.RemoveField(
            model_name='quarterlyholding',
            name='filedOn',
        ),
        migrations.AddField(
            model_name='security',
            name='cikCusipMappingId',
            field=models.TextField(blank=True, default=None),
        ),
    ]
