# Generated by Django 3.0.5 on 2021-02-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0002_auto_20210202_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='companyId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='security',
            name='securityName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='security',
            name='securityType',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='security',
            name='ticker',
            field=models.CharField(max_length=5),
        ),
    ]
