# Generated by Django 3.0.5 on 2020-10-04 23:49

from django.db import migrations, models

# file deepcode ignore django~null~true~nontext~field: <comment the reason here>
class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0002_auto_20201004_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='cikcusipmapping',
            name='cikCusipMappingId',
            field=models.TextField(blank=True, default=None),
        ),
    ]
