# Generated by Django 3.0.5 on 2020-12-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgar', '0004_auto_20201004_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='cikCusipMappingId',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
