# Generated by Django 3.0.5 on 2020-07-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=100)),
                ('desc',
                 models.TextField()),
                ('price',
                 models.IntegerField()),
                ('offer',
                 models.BooleanField(
                     default=False)),
            ],
        ),
    ]
