# Generated by Django 3.0.5 on 2020-08-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedgehund_profile', '0002_auto_20200801_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
