# Generated by Django 3.0.5 on 2020-08-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedgehund_profile', '0003_remove_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprof',
        ),
    ]
