# Generated by Django 3.0.5 on 2020-08-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedgehund_profile', '0004_delete_userprof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
