# Generated by Django 3.0.5 on 2020-08-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedgehund_profile', '0005_auto_20200801_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
