# Generated by Django 3.0.5 on 2020-08-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedgehund_profile', '0006_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
