# Generated by Django 3.0.5 on 2021-02-07 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('name', models.TextField(max_length=80)),
                ('cik', models.TextField(blank=True)),
                ('filer_type', models.TextField(blank=True)),
                ('cusip', models.TextField(blank=True, max_length=10)),
                ('filerId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(blank=True, default=None)),
                ('deletedAt', models.DateTimeField(blank=True, default=None)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('name', models.TextField(blank=True)),
                ('symbol', models.TextField(blank=True, max_length=7)),
                ('titleOfClass', models.TextField(blank=True)),
                ('sector', models.TextField(blank=True)),
                ('securityId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(blank=True, default=None)),
                ('deletedAt', models.DateTimeField(blank=True, default=None)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('quarter', models.TextField()),
                ('quarterId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(blank=True, default=None)),
                ('deletedAt', models.DateTimeField(blank=True, default=None)),
                ('filerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdings.Filer')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('quarterFirstOwned', models.TextField(blank=True)),
                ('investmentDiscretion', models.TextField(blank=True)),
                ('quantity', models.FloatField(blank=True)),
                ('marketValue', models.FloatField(blank=True)),
                ('weightPercent', models.FloatField(blank=True)),
                ('previousWeightPercent', models.FloatField(blank=True)),
                ('estimatedAverageCost', models.FloatField(blank=True)),
                ('lastPrice', models.FloatField(blank=True)),
                ('estimatedProfit', models.FloatField(blank=True)),
                ('ranking', models.FloatField(blank=True)),
                ('changeInShares', models.FloatField(blank=True)),
                ('changeInPositionPercent', models.FloatField(blank=True)),
                ('sourceType', models.TextField(blank=True)),
                ('sourcedOn', models.DateTimeField(blank=True)),
                ('positionType', models.TextField(blank=True)),
                ('positionId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(blank=True, default=None)),
                ('deletedAt', models.DateTimeField(blank=True, default=None)),
                ('quarterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_Id', to='holdings.Quarter')),
                ('securityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdings.Security')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
