# Generated by Django 3.0.5 on 2021-04-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={},
        ),
    ]
